### PR TITLE
Changed to python3 beca Installed by default more.

### PR DESCRIPTION
**Pull request by mhmatthewhugley**
I just changed it to use python 3 because that is installed by default on more linux distributions then "python"

### CODE REVIEW

**Comment by agude** [comment]
Hi! Thanks for your patch, but we're already on Python3 (as you can see in the test suit, [here](https://github.com/agude/wayback-machine-archiver/blob/master/.github/workflows/tests.yml#L10)). The shebang line in the setup shouldn't really matter since it's not run directly anyway; it's mainly so my editor knows how to highlight.

**Comment by mhmatthewhugley** [comment]
Ah, well on Linux Mint it would not install until the number 3 was added because it seems like there is not a symbolic link linking "python" to "python3" by default on Linux Mint.

**Comment by agude** [comment]
@mhmatthewhugley Weird, I've never seen that behavior! Are you using the right `pip`? It should just be `pip install .` from the directory (or possibly `pip3` for Mint) or `pip install wayback-machine-archiver` to get it from pypi (again, you might need write `pip3` instead).

As an aside, I recommend using something like `pyenv` to create Python installation separate from the system version. It lets you have multiple different Python versions, and each one can be tailored to a single job. This is a pretty good intro: https://akrabat.com/creating-virtual-environments-with-pyenv/

**Comment by mhmatthewhugley** [comment]
> @mhmatthewhugley Weird, I've never seen that behavior! Are you using the right `pip`? It should just be `pip install .` from the directory (or possibly `pip3` for Mint) or `pip install wayback-machine-archiver` to get it from pypi (again, you might need write `pip3` instead).
> 
> As an aside, I recommend using something like `pyenv` to create Python installation separate from the system version. It lets you have multiple different Python versions, and each one can be tailored to a single job. This is a pretty good intro: https://akrabat.com/creating-virtual-environments-with-pyenv/

I originally tried "pip install wayback-machine-archiver" that did not work so I did some other method and eventually ended up getting it to work by doing what I said above. I am like 50 percent sure I could have got it working by changing it to pip3 but I am too lazy to try it.

**Pull request closed without merging**
